### ISSUE TITLE
QUESTION - Can I create JSON from HTML with this code?

### ISSUE THREAD

**Issue by rodfersou** [springload/draftjs_exporter#115]
My use case need to migrate rich text content into JSON used in DraftJS, is it possible to do this with this code?

**Comment by thibaudcolas** [comment]
Hey @rodfersou 👋 no, this library is Draft.js JSON -> HTML only, it doesn’t cover the other way around. [draft-convert](https://github.com/HubSpot/draft-convert) supports HTML -> Draft.js, but that’s a Node package.

**Comment by rodfersou** [comment]
@thibaudcolas thanks for the answer
