### ISSUE TITLE
[WIP] Corner cases to address

### ISSUE THREAD

**Issue by thibaudcolas** [springload/draftjs_exporter#4]
Discuss the tricky problems the exporter needs to address. They can be addressed by "doing the right thing", documenting the shortcomings, and/or letting the user configure the output they want.

- [x] Custom attributes (not `data-*` attributes but invalid ones like `*ngFor`) – ok with html5lib
- [x] Order in which ranges are applied (`em` in `strong` or `strong` in `em`)
  - Stable (alphabetical) order for now, but not configurable.
- [x] Order in which attributes are rendered can be different between Python versions - use something like `from collections import OrderedDict`?
  - html5lib inserts attributes in alphabetical order
- [x] Nested blocks where nesting jumps one level of depth (depth = 1, then depth = 3)
  - Not supported for now
- [x] `unstyled` blocks without text, should they render as empty `p` tags? `br`?
  - Empty elements for now.

**Comment by JoshBarr** [comment]
We've discussed possibly providing a list of the order of operations for inline ranges. Eg, `code` should be the innermost range.
