### ISSUE TITLE
Add configuration options to determine handling of missing components

### ISSUE THREAD

**Issue by thibaudcolas** [springload/draftjs_exporter#52]
Copy/pasting @loicteixeira's point about the current exceptions:

> Something to consider as well is whether the renderer should crash when there is a component it doesn’t know about it, or if it should ignore it? Maybe a settings in `draftjs_exporter` like `RAISE_MISSING_BLOCK_ERRORS` which we will probably set to the same value as `DEBUG`.

**Comment by thibaudcolas** [comment]
I've thought about this a bit more, and I think it could be enough to provide component fallbacks then let people in complete control over the handling and potential logging. 

There would be:

- `block_fallback` with access to block type, data, and depth (and its children)
- `style_fallback` with access to style type (and its children)
- `entity_fallback` with access to entity type, data (and its children)

If one of those is specified, the related exceptions would simply not be raised. Then, any logging or replacement behaviour can be handled with those fallbacks. "it's just functions", which allows more flexibility, and doesn't require adding too much logging code in the exporter itself.

**Comment by loicteixeira** [comment]
That's quite a bit of boilerplate but is certainly much more extensible so let's do this.
