### ISSUE TITLE
Add benchmarking tests with real-world content

### ISSUE THREAD

**Issue by thibaudcolas** [springload/draftjs_exporter#65]
At the moment the `exports` test suite is used to measure performance. While the content in it is significant, it's not really representative of real-world workloads.

Once someone has an open-source site using this, I would be keen to dump all of its content in this repository so we have more relevant numbers to look at.

**Comment by su27** [comment]
Well my work is not in an open-source site, but most of the content (like notes and reviews) are public, I think maybe I could help to evaluate the performance in some way.
