### ISSUE TITLE
Allow content on element even if not configured

### ISSUE THREAD

**Issue by lucasts** [springload/draftjs_exporter#71]
Before upgrading, we used `unstyled` as a empty string `''`

After 0.8(if I'm not mistaken)  draftjs_exporter
will create a empty text instead of original text content

**Comment by lucasts** [comment]
I could hack it using unstyled as `fragment`

**Comment by thibaudcolas** [comment]
I'm not exactly sure what your issue is, but if you found a way to make it work for you I'm glad 👌.

**Comment by lucasts** [comment]
@thibaudcolas I need to clarify a bit so other people may find this issue helpful.

We were using `draftjs_exporter==0.4.0` defining a unstyled block map like this:
```
block_map['unstyled'] = '{"element": ""}'
```
if my element had some text like `"text": "some text"`
draftjs_exporter would render `some text`

with `1.0.0` we would update to 
```
block_map['unstyled'] = ""
```
and for the same element above would print `''`

my fix was to define unstyled this way:
```
block_map['unstyled'] = "fragment"
```

so draftjs_exporter will print it correctly `some text`

**Comment by thibaudcolas** [comment]
Ah, gotcha. I see how this would work, but `fragment` is only meant as an internal implementation detail, not a public API. That said it's unlikely to be changed any time soon (the internals are fairly stable as-is), and any change to something as fundamental would be semver breaking/major, so you're good to go for a long while 👍.

Here is the supported way to achieve the same output:

```python
# Use a function returning the block's content
block_map['unstyled'] = lambda props: props['children']
```
