### ISSUE TITLE
Improve dependencies compatibility definition, and testing

### ISSUE THREAD

**Issue by thibaudcolas** [springload/draftjs_exporter#75]
Raised by @loicteixeira in https://github.com/springload/draftjs_exporter/pull/74/files#r135967185. Opening as a separate issue because it's worth discussing and there is no point in holding that PR for this.

At the moment, `draftjs_exporter` defines its dependencies as:

https://github.com/springload/draftjs_exporter/blob/c963514cf0d81261677376d4323655e9efbb88cd/setup.py#L15-L22

Those ranges are purposefully big (we want to support as many versions as possible for something as fundamental to people's tech stacks), which is good, but as @loicteixeira puts it then it would make sense to test accordingly, with the lower and upper bounds at least.

----

More info to help in the decision,

- lxml at 3.6.0 is the version I used locally. Seems like now there is 3.8.0 (https://pypi.python.org/pypi/lxml), might make sense to add an upper bound in `setup.py` to limit installed versions to below 4.0.0?
- The BeautifulSoup4 / html5lib versions are loosely aligned with requirements from Wagtail: https://github.com/wagtail/wagtail/blob/a7820a2e903a560d6ceb73062ab9ba922f23b0dc/setup.py#L30-L31

```py
    "beautifulsoup4>=4.5.1",
    "html5lib>=0.999,<1",
```

Finally, bear in mind that our usage of the APIs of those dependencies is very small (HTML string -> DOM nodes conversion, DOM nodes -> HTML string conversion, create nodes, append child to node), which means that the potential breakage would only likely be in how those engines handle specific content, which is hard to test for. We do however have a small test suite of "potential engine quirks": https://github.com/springload/draftjs_exporter/blob/master/tests/engines/test_engines_differences.py

**Comment by loicteixeira** [comment]
I reckon it's safer to have an upper bound for both for now as we can always increase it later once we confirm everything is working rather than having to rush a patch.

 `beautifulsoup4>=4.4.1,<5` and `lxml>=3.6.0,<4` would be a good start.

If you're ok with that I'll update the test-matrix and documentation when I have a moment.

**Comment by thibaudcolas** [comment]
Sounds good!

**Comment by thibaudcolas** [comment]
lxml 4.0.0 has been released in september and I can confirm 4.1.1 works fine, so I'd suggest going for `lxml>=3.6.0,<5`.
