### ISSUE TITLE
Change default engine to the new dependency-free one introduced in #77

### ISSUE THREAD

**Issue by thibaudcolas** [springload/draftjs_exporter#79]
The exporter now has an engine that doesn't have any dependencies. It should probably be the one activated by default, to make the whole package dependency-free unless another engine is configured. It also happens to be faster, and less memory-hungry.

This is a breaking change though, no matter how little difference there is with the output of the current default (html5lib + BeautifulSoup), so should be part of the 2.0.0 release.

As part of this change, it will also be necessary to move the html5lib / BS4 dependencies to a separate extra like for lxml (`pip install draftjs_exporter[html5lib]`), as well as update the documentation.

**Comment by loicteixeira** [comment]
I remember us talking about loading engines via string path, which would also solve #79 but I can't find the corresponding issue or PR.

**Comment by thibaudcolas** [comment]
👍  let's try to do this at the same time then. Thanks for tracking this down.

**Comment by thibaudcolas** [comment]
@loicteixeira in those comments you say you were keen on _not_ having a default engine at all, thus forcing users of the exporter to make a more explicit choice (and also helping make sure they install the right dependencies).

Now that the new potential engine does not have dependencies, do you think this is still relevant?

**Comment by loicteixeira** [comment]
No you're right, it's no longer relevant.
