### ISSUE TITLE
[WIP] HTML building libraries to try out

### ISSUE THREAD

**Issue by thibaudcolas** [springload/draftjs_exporter#8]
- [x] https://github.com/html5lib/html5lib-python for its nicer API, but no documentation
- [ ] http://pythonhosted.org/pyquery/ for its nicer API (?), documented, built on top of lxml

**Comment by ThibWeb** [comment]
Start by wrapping DOM manipulations in a separate module before moving from lib A to lib B

**Comment by ThibWeb** [comment]
https://github.com/springload/draftjs_exporter/blob/master/draftjs_exporter/dom.py is now the only spot where lxml-related code has to be changed for the exporter and its tests to use something else instead.

I gave it a first try in https://github.com/springload/draftjs_exporter/tree/feature/beautifulsoup-test, but this is proving complicated so I'll hold off for now. Best would be to use html5lib directly, but it doesn't really feel ready for prime time.
