### ISSUE TITLE
Unicode decode reading markdown file

### ISSUE THREAD

**Issue by thenewguy** [springload/draftjs_exporter#96]
Ubuntu 16.04

python 3.5

```
Collecting draftjs_exporter (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/c3/98/2ae0db16e3841d9d0623b1a2248987e1edd037ab7eaa04e45e4fdf18873b/draftjs_exporter-2.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-f_emtego/draftjs-exporter/setup.py", line 38, in <module>
        long_description = f.read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1956: ordinal not in range(128)
```

**Comment by thenewguy** [comment]
Problem code located.  This commit allows for successful installation: https://github.com/thenewguy/draftjs_exporter/commit/e20a8d44c6ca4af28b845bf2bec480a26fc1b6f3

**Comment by thenewguy** [comment]
Hitting this on a lot of things. Closing again.  Thinking it has something to do with defaults set in my docker image now

**Comment by thibaudcolas** [comment]
👌this seems to work fine for me with Python 3.5 on macOS 10.13. The setup.py is something we don't test in CI – let me know if you think we could improve on that.

Related: #95.

**Comment by thenewguy** [comment]
This was not related to your project.  Combination of pip bug and some other environment issues.  I got them straightened out and confirmed it was not something specific to this project
